/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Adds two integers on the main thread.
 *
 * A trivial **synchronous** export: it returns immediately, so there is no
 * benefit to running it off-thread. Reach for this shape when the work is
 * cheap and non-blocking.
 */
export declare function add(a: number, b: number): number

/**
 * Sums `0..=n`, off the main thread.
 *
 * Marked `async` so napi runs it on the libuv thread pool: the Node event
 * loop stays free while this churns, so slow CPU-bound work here never blocks
 * other requests. This is the shape to reach for with heavy computation.
 *
 * Returned as `f64` (JS `number`) to sidestep integer overflow for large `n`.
 */
export declare function sumTo(n: number): Promise<number>
