/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Builds the shared index if this process hasn't yet, and returns its stats.
 *
 * `async` because the one-time build is real work (~hundreds of ms): napi
 * runs it on the worker pool so the Node event loop never blocks, even on the
 * unlucky first request. Every subsequent call returns the cached stats.
 */
export declare function ensureIndex(): Promise<IndexStats>

/** Stats for the shared index (also proof it exists). */
export interface IndexStats {
  /** Number of documents in the index. */
  docCount: number
  /**
   * Wall-clock milliseconds the one-time index build took (parse + index +
   * commit). Paid once per process, by whichever request arrives first.
   */
  buildMs: number
}

/**
 * Ranked full-text search over the corpus; returns up to `limit` hits
 * (1–50, 0 means the default of 10).
 *
 * Deliberately **synchronous**: once the index is warm a query is tens of
 * microseconds, far below the cost of a thread-pool hop, so this stays on
 * the main thread (the async-by-convention rule cuts both ways). Call
 * `ensureIndex()` first — if the index isn't built yet, this builds it
 * synchronously and the event loop pays for it.
 */
export declare function search(query: string, limit: number): Array<SearchHit>

/** One ranked search result. */
export interface SearchHit {
  /** The document title, verbatim from the corpus. */
  title: string
  /** tantivy's BM25 relevance score (higher = better match). */
  score: number
  /**
   * Body snippet as HTML: matched terms wrapped in `<b>`, all other text
   * HTML-escaped by tantivy's snippet generator, so it is safe to render.
   */
  snippet: string
}
