/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Hashes a password with Argon2id — **async, off the event loop**.
 *
 * `async fn` makes napi-rs run the hash on its worker pool and hand JS a
 * `Promise<string>`. The event loop stays free: N concurrent calls run in
 * parallel across cores, finishing in ~1 × 100 ms wall time while the server
 * keeps serving other requests. This is the shape to ship.
 *
 * Returns a PHC-format string (`$argon2id$v=19$m=65536,t=3,p=1$...`) that
 * embeds the salt and parameters, ready to store as-is.
 */
export declare function hashPassword(password: string): Promise<string>

/**
 * Hashes a password with Argon2id — **synchronously, on the main thread**.
 *
 * This export exists to demonstrate the anti-pattern: a plain (non-async)
 * `#[napi]` fn runs on the Node.js main thread, so the ~100 ms of deliberate
 * argon2 work blocks the event loop for its entire duration. N concurrent
 * calls serialize into N × 100 ms of a completely unresponsive server.
 * Don't ship this shape for slow work — see `hash_password`.
 */
export declare function hashPasswordSync(password: string): string

/**
 * Verifies a password against a stored PHC-format hash, off the event loop.
 *
 * Demonstrates Rust `Result` → JS exception propagation:
 * - wrong password → resolves `false` (an expected outcome, not an error)
 * - malformed / corrupted hash string → returns `Err`, which napi-rs turns
 *   into a **rejected Promise** — a normal catchable JS exception carrying
 *   this message. No panics, no process crashes.
 */
export declare function verifyPassword(password: string, hash: string): Promise<boolean>
