/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Result object for [`thumbnail`]: the encoded bytes plus an honest
 * per-phase timing breakdown measured inside Rust.
 */
export interface EncodedImage {
  /**
   * Encoded WebP/AVIF bytes. `Buffer` here becomes a Node `Buffer` without
   * an intermediate copy into a JS array.
   */
  data: Buffer
  /** Output width in pixels. */
  width: number
  /** Output height in pixels. */
  height: number
  /** Encoded size in bytes (`data.length`, pre-computed for display). */
  bytes: number
  /** Milliseconds spent decoding the input (JPEG/PNG -> RGBA). */
  decodeMs: number
  /** Milliseconds spent in the SIMD Lanczos3 resize. */
  resizeMs: number
  /** Milliseconds spent encoding (WebP or AVIF). */
  encodeMs: number
}

/**
 * Decode -> SIMD resize -> WebP/AVIF encode, entirely off the event loop.
 *
 * `async` puts the whole pipeline on napi's worker pool, and `ravif`'s
 * rayon-backed encoder fans the AV1 work across cores from there — the Node
 * event loop stays free for other requests the entire time.
 *
 * Buffer in, Buffer out: the input is the raw bytes of a JPEG/PNG file; the
 * result carries the encoded image plus a decode/resize/encode ms breakdown.
 */
export declare function thumbnail(input: Buffer, opts: ThumbOpts): Promise<EncodedImage>

/**
 * Options object for [`thumbnail`] — the napi "options struct" pattern.
 *
 * `#[napi(object)]` maps a plain Rust struct to a plain JS object (by-value,
 * no class wrapper), so the JS call site reads naturally:
 * `thumbnail(buf, { width: 480, format: "webp", quality: 60 })`.
 */
export interface ThumbOpts {
  /** Target width in pixels (16–2048). Height preserves the aspect ratio. */
  width: number
  /**
   * Output codec. `ts_type` narrows the generated TS to a string union, so
   * invalid formats are a *compile-time* error in TS and a validated
   * `InvalidArg` at runtime from JS.
   */
  format: "webp" | "avif"
  /** Encoder quality, 1–100 (WebP quality / AVIF quantizer scale). */
  quality: number
}
