/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Transform untrusted email HTML: UTM-tag links + inline classes in one
 * lol_html streaming pass, then sanitize with ammonia.
 *
 * `async` per this repo's convention: the whole transform runs on napi's
 * worker pool, so a large document never blocks the Node event loop.
 */
export declare function transformHtml(html: string, opts: TransformOpts): Promise<TransformResult>

/**
 * Options for [`transform_html`]. `#[napi(object)]` maps this to a plain JS
 * object literal (fields arrive camelCased: `utmSource`, `inlineStyles`,
 * `sanitize`).
 */
export interface TransformOpts {
  /**
   * Value for the appended `utm_source` query param. An empty string
   * disables link rewriting.
   */
  utmSource: string
  /** Apply the fixed class → inline-style map and drop `class` attributes. */
  inlineStyles: boolean
  /** Run the ammonia sanitization stage. */
  sanitize: boolean
}

/**
 * Result of [`transform_html`]: the transformed HTML plus per-stage timings
 * and a diff-ish summary of what changed.
 */
export interface TransformResult {
  /** The transformed (and, if requested, sanitized) HTML. */
  html: string
  /**
   * Milliseconds spent in the single lol_html streaming pass
   * (link rewriting + class inlining).
   */
  rewriteMs: number
  /** Milliseconds spent in ammonia sanitization (0 when `sanitize` is off). */
  sanitizeMs: number
  /** Input size in bytes (UTF-8). */
  bytesIn: number
  /** Output size in bytes (UTF-8). */
  bytesOut: number
  /** `<a href>` links that had UTM params appended. */
  linksRewritten: number
  /** Class names that were mapped to inline styles. */
  classesInlined: number
  /**
   * Dangerous elements (script/style/iframe/object/embed) removed by
   * sanitization. Counted by tag rather than by total element diff:
   * ammonia's html5ever parser normalizes the tree (e.g. inserts missing
   * `<tbody>`), so a raw before/after element count would lie.
   */
  elementsRemoved: number
}
