// Server-only entry point for the native Rust addon.
//
// NOTE the difference from the react-router example: Remix 3 has NO Vite
// pipeline, so vite-plugin-native-rust cannot sit in front of it and the
// `import { add } from "../native/src/lib.rs"` sugar is unavailable. Instead
// the crate is compiled ahead of time with `npm run build:native` (napi build
// --release → native/remixdemo.node + native/index.d.ts) and loaded here with
// a plain `require()` of the .node addon. Same crate, same napi-rs contract,
// no plugin.
//
// The `.server.ts` suffix is kept as a convention only — Remix 3 has no client
// bundle graph to protect; everything in app/ runs on the server unless it is
// explicitly served as a browser asset.
import { existsSync } from 'node:fs'
import { createRequire } from 'node:module'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'

/**
 * Exports of native/src/lib.rs as generated by napi-rs (see native/index.d.ts,
 * regenerated on every `npm run build:native`). Kept as a hand-written mirror
 * so `tsc --noEmit` passes even before the first native build.
 */
interface RemixDemoAddon {
  /** Sync add — runs on the main thread. */
  add(a: number, b: number): number
  /** Async sum 0..=n — runs on napi-rs's worker pool, off the event loop. */
  sumTo(n: number): Promise<number>
}

function sourceRelativeCandidate(): string | null {
  // `import.meta.url` is a file: URL when running from source via the
  // remix/node-tsx loader; bundlers may rewrite or drop it, hence the guard.
  try {
    if (typeof import.meta.url === 'string' && import.meta.url.startsWith('file:')) {
      return fileURLToPath(new URL('../native/remixdemo.node', import.meta.url))
    }
  } catch {
    return null
  }
  return null
}

function resolveAddonPath(): string {
  const candidates = [
    sourceRelativeCandidate(),
    // Bundled deploys (e.g. the Vercel function, where app code is compiled
    // into the function body): resolve from the app root instead.
    path.join(process.cwd(), 'native', 'remixdemo.node'),
  ].filter((candidate): candidate is string => candidate !== null)

  const found = candidates.find((candidate) => existsSync(candidate))
  if (!found) {
    throw new Error(
      'Native addon not found — run `npm run build:native` first. Looked in:\n' +
        candidates.map((candidate) => `  - ${candidate}`).join('\n'),
    )
  }
  return found
}

function loadAddon(): RemixDemoAddon {
  const addonPath = resolveAddonPath()
  // createRequire is anchored to a real on-disk path (not import.meta.url) so
  // this also works if a bundler compiles this module into another file.
  const requireAddon = createRequire(addonPath)
  const addon = requireAddon(addonPath) as Partial<RemixDemoAddon>
  if (typeof addon.add !== 'function' || typeof addon.sumTo !== 'function') {
    throw new Error(
      `Loaded ${addonPath} but it is missing the expected add/sumTo exports. ` +
        'Rebuild it with `npm run build:native`.',
    )
  }
  return addon as RemixDemoAddon
}

const addon = loadAddon()

export const add: RemixDemoAddon['add'] = addon.add
export const sumTo: RemixDemoAddon['sumTo'] = addon.sumTo
