/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Trivial synchronous export — exists so the plugin can exercise
 * named-export enumeration over a mix of sync/async functions.
 */
export declare function add(a: number, b: number): number

/**
 * CPU-bound SHA-256 hash chain, mirroring heavy.server.ts::heavyHashChain.
 *
 * `async` so napi runs it on the libuv thread pool: the Node event loop is
 * never blocked while this churns. Returns the final digest as a hex string.
 */
export declare function hashChain(iterations: number): Promise<string>
